= API 繧ｭ繝ｼ縺ｮ莉墓ｧ・:sectnums:

== 縺ｯ縺倥ａ縺ｫ

縺薙・譁・嶌縺ｧ縺ｯ API 繧ｭ繝ｼ縺ｮ莉墓ｧ倥ｒ螳夂ｾｩ縺励※縺・∪縺吶・
API 繧ｭ繝ｼ縺ｯ縲∫音螳壹・繝ｦ繝ｼ繧ｶ繝ｼ繧・た繝輔ヨ繧ｦ繧ｧ繧｢繧ｵ繝ｼ繝薙せ縺ｫ蟇ｾ縺励※ API 縺ｸ縺ｮ繧｢繧ｯ繧ｻ繧ｹ繧貞宛蠕｡縺吶ｋ縺溘ａ縺ｮ隱崎ｨｼ諠・ｱ縺ｧ縺吶・API 繧ｭ繝ｼ繧剃ｽｿ逕ｨ縺吶ｋ縺薙→縺ｧ縲√Μ繧ｯ繧ｨ繧ｹ繝医′豁｣蠖薙↑繧ゅ・縺ｧ縺ゅｋ縺薙→繧堤｢ｺ隱阪＠縲∽ｸ肴ｭ｣繧｢繧ｯ繧ｻ繧ｹ繧帝亟豁｢縺励∪縺吶・
WDTO 縺ｯ縲、PI 繧剃ｻ九＠縺ｦ繝ｦ繝ｼ繧ｶ繧・し繝ｼ繝薙せ縺ｫ繝ｭ繧ｱ繝ｼ繧ｷ繝ｧ繝ｳ繧・ョ繝舌う繧ｹ縺ｪ縺ｩ縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧呈署萓帙＠縺ｾ縺吶・縺薙ｌ繧峨・繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｯ繧ｫ繧ｹ繧ｿ繝槭＃縺ｨ縺ｮ諠・ｱ縺ｧ縺ゅｋ縺溘ａ縲、PI 繧貞茜逕ｨ縺吶ｋ繝ｦ繝ｼ繧ｶ繧・し繝ｼ繝薙せ縺ｫ蠢懊§縺ｦ蜿ら・繧・峩譁ｰ蜿ｯ閭ｽ縺ｪ繝ｪ繧ｽ繝ｼ繧ｹ繧貞宛髯舌☆繧句ｿ・ｦ√′縺ゅｊ縺ｾ縺吶・縺昴・縺溘ａ縲、PI 繧ｭ繝ｼ縺ｫ縺ｯ縲∽ｻ･荳九・繧医≧縺ｫ API 繧ｭ繝ｼ繧呈戟縺､繧ｪ繝ｼ繝頑ュ蝣ｱ縺ｨ繧｢繧ｯ繧ｻ繧ｹ縺瑚ｨｱ蜿ｯ縺輔ｌ繧九Μ繧ｽ繝ｼ繧ｹ諠・ｱ繧偵・繝ｪ繧ｷ縺ｨ縺励※邏舌▼縺代∪縺吶・
....
{
  "policies": {
    "effect": "Allow",
    "actions": ["List"],
    "ownerId": "575e4f6a-22e8-4763-b352-f60006735c3d",
    "resources": [{
        "customerId": "575e4f6a-22e8-4763-b352-f60006735c3d",
        "resourceType": "device"
    }]
  }
}
....

繧ｵ繝ｼ繝薙せ繧・き繧ｹ繧ｿ繝・(API 繧ｭ繝ｼ縺ｮ繧ｪ繝ｼ繝・ 縺・WDTO 縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｫ繧｢繧ｯ繧ｻ繧ｹ縺吶ｋ縺ｫ縺ｯ縲∽ｻ･荳九・繧医≧縺ｫ API 繧ｭ繝ｼ繧・Web API 縺ｮ繝ｪ繧ｯ繧ｨ繧ｹ繝医・繝・ム縺ｫ險ｭ螳壹＠縺ｾ縺吶・縺薙・繧医≧縺ｫ縺吶ｋ縺薙→縺ｧ縲√◎縺ｮ繧ｪ繝ｼ繝翫↓險ｱ蜿ｯ縺輔ｌ縺溘Μ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｮ縺ｿ繧貞茜逕ｨ縺ｧ縺阪ｋ繧医≧縺ｫ縺ｪ繧翫∪縺吶・
....
GET /devices
wdto-api-key: f75646d2-d74b-4fdd-8dd3-8fbefe985d86

{
  "totalItems": 100,
  "page": 1,
  "itemsPerPage": 20,
  "totalPages": 20,
  "devices": [
    {
      "id": "c76c765b-4e22-32b8-f31e-3649f5825b40",
      "locationId": "c76c765b-4e22-32b8-f31e-3649f5825b4X",
      "customerId": "575e4f6a-22e8-4763-b352-f60006735c3d",
      "serialNumber": "2343FD1NKQ38",
      "name": "Logitech vr0020",
      "model": "Rally Bar",
      "manufacturer": "Logitech",
      "createdAt": "2023-10-01T12:00:00.000Z",
      "updatedAt": "2023-10-01T12:00:00.000Z",
    }
  ]
}
....

== API 繧ｭ繝ｼ縺ｮ遞ｮ鬘・
API 繧ｭ繝ｼ縺ｯ縲・遞ｮ鬘槭↓蛻・｡槭＆繧後∪縺吶・
=== 繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ

繝ｦ繝ｼ繧ｶ繧・し繝ｼ繝薙せ縺後Μ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｫ繧｢繧ｯ繧ｻ繧ｹ縺吶ｋ縺溘ａ縺ｮ API 繧ｭ繝ｼ縺ｧ縺吶・Web API 縺ｮ繝倥ャ繝縺ｫ險ｭ螳壹☆繧九％縺ｨ縺ｧ縲√Μ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｮ蜿ら・繧・峩譁ｰ縺悟庄閭ｽ縺ｫ縺ｪ繧翫∪縺吶・繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ縺ｮ API 繧ｭ繝ｼ縺ｯ隱ｰ縺ｧ繧ら匱陦後〒縺阪ｋ繧上￠縺ｧ縺ｯ縺ゅｊ縺ｾ縺帙ｓ縲ゅ窟PI 繧ｭ繝ｼ逋ｺ陦檎畑 API 繧ｭ繝ｼ縲阪′蠢・ｦ√〒縺吶・
=== API 繧ｭ繝ｼ逋ｺ陦檎畑 API 繧ｭ繝ｼ

縺薙・ API 繧ｭ繝ｼ繧貞茜逕ｨ縺吶ｋ縺薙→縺ｧ縲√後ョ繝ｼ繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ縲阪ｒ逋ｺ陦後☆繧九％縺ｨ縺後〒縺阪∪縺吶・縺薙・ API 繧ｭ繝ｼ縺ｯ縲仝DTO 縺ｮ驕狗畑邂｡逅・・(WDTO 邂｡逅・・ 縺九ｉ縲仝DTO 繧貞茜逕ｨ縺吶ｋ繧ｵ繝ｼ繝薙せ縺ｮ邂｡逅・・(繧ｵ繝ｼ繝薙せ邂｡逅・・ 縺ｫ謠蝉ｾ帙＆繧後∪縺吶・
== API 繧ｭ繝ｼ縺ｮ逋ｺ陦御ｽ懈･ｭ

WDTO 縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧貞茜逕ｨ縺ｧ縺阪ｋ繧医≧縺ｫ縺ｪ繧九◆繧√・繝輔Ο繝ｼ縺ｯ莉･荳九・繧医≧縺ｫ縺ｪ繧翫∪縺吶・
ifdef::env-github[]
[source,mermaid]
endif::[]

ifndef::env-github[]
[mermaid]
endif::[]
....
flowchart TD
    A["縲晋DTO 邂｡逅・・・br/>繧ｵ繝ｼ繝薙せ逋ｻ骭ｲ<br/>(POST /sp/services)"] --> B["縲晋DTO 邂｡逅・・・br/>API 繧ｭ繝ｼ逋ｺ陦檎畑 API 繧ｭ繝ｼ逋ｺ陦・br/>(POST /api-keys)"]
    B --> C["縲舌し繝ｼ繝薙せ邂｡逅・・・br/>繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ逋ｺ陦・br/>(POST /api-keys)"]
    C --> D["縲舌き繧ｹ繧ｿ繝槭・br/>繧ｵ繝悶せ繧ｯ繝ｪ繝励す繝ｧ繝ｳ逋ｻ骭ｲ<br/>(POST /subscriptions)"]
    C --> E["縲舌き繧ｹ繧ｿ繝槭・br/>繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ蜿ら・<br/>(GET /devices, GET /locations)"]
    C --> F["縲舌し繝ｼ繝薙せ縲・br/>繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ逋ｻ骭ｲ<br/>(POST /devices, POST /locations)"]
....


<<api-keys-service-registration>>縺ｨ<<api-keys-issue-api-key>>縺ｯ WDTO 邂｡逅・・′陦後≧菴懈･ｭ縺ｧ縲・<<api-keys-issue-data-access-key>>縺ｯ繧ｵ繝ｼ繝薙せ邂｡逅・・′陦後≧菴懈･ｭ縺ｧ縺吶・縺ｪ縺翫・<api-keys-issue-data-access-key>>縺ｧ縺ｯ縲仝DTO 縺檎ｮ｡逅・☆繧九き繧ｹ繧ｿ繝・ID 縺悟ｿ・ｦ√〒縺吶・繧ｫ繧ｹ繧ｿ繝・ID 繧貞性繧繧ｫ繧ｹ繧ｿ繝樊ュ蝣ｱ縺ｯ縲仝DTO 邂｡逅・・↓繧医▲縺ｦ莠句燕縺ｫ WDTO 縺ｫ逋ｻ骭ｲ縺輔ｌ縺ｦ縺・∪縺吶・
[[api-keys-wdto-admin-flow]]
=== WDTO 邂｡逅・・・菴懈･ｭ

WDTO 邂｡逅・・・莉･荳九・菴懈･ｭ繧偵＠縺ｾ縺吶ゅ％縺ｮ菴懈･ｭ縺ｫ縺ｯ WDTO 縺ｮ邂｡逅・・い繧ｫ繧ｦ繝ｳ繝医′蠢・ｦ√〒縺吶・
. <<api-keys-service-registration>>
. <<api-keys-issue-api-key>>

[[api-keys-service-registration]]
==== WDTO 繧貞茜逕ｨ縺吶ｋ縲後し繝ｼ繝薙せ縲阪・逋ｻ骭ｲ

縲窟PI 繧ｭ繝ｼ逋ｺ陦檎畑 API 繧ｭ繝ｼ縲阪ｒ逋ｺ陦後☆繧九◆繧√↓縺ｯ縲仝DTO 繧貞茜逕ｨ縺吶ｋ縲後し繝ｼ繝薙せ縲阪・ ID 縺悟ｿ・ｦ√〒縺吶・莉･荳九・繧医≧縺ｫ Web API (`POST /sp/services`) 繧貞茜逕ｨ縺吶ｋ縺薙→縺ｧ縲√し繝ｼ繝薙せ縺ｮ ID 繧貞叙蠕励〒縺阪∪縺吶・縺ｪ縺翫、uthorization 繝倥ャ繝縺ｫ縺ｯ縲仝DTO 縺ｮ邂｡逅・・い繧ｫ繧ｦ繝ｳ繝医・ Basic 隱崎ｨｼ諠・ｱ繧呈欠螳壹＠縺ｾ縺吶・
....
POST /sp/services
Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l

{
  "name": "繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ",
  "description": "萓九→縺励※逋ｻ骭ｲ縺吶ｋ繧ｵ繝ｼ繝薙せ縺ｧ縺・,
}
....

繧ｵ繝ｼ繝薙せ縺ｮ逋ｻ骭ｲ縺ｫ謌仙粥縺吶ｋ縺ｨ縲∽ｻ･荳九・繧医≧縺ｫ繧ｵ繝ｼ繝薙せ ID (`serviceId`) 縺梧署萓帙＆繧後∪縺吶・縺薙・繧ｵ繝ｼ繝薙せ ID 縺ｯ API 繧ｭ繝ｼ縺ｮ逋ｺ陦後〒蠢・ｦ√〒縺吶・
....
{
  "serviceId": "550e8400-e29b-41d4-a716-446655440000",
  "name": "繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ",
  "description": "萓九→縺励※逋ｻ骭ｲ縺吶ｋ繧ｵ繝ｼ繝薙せ縺ｧ縺・
}
....

[[api-keys-issue-api-key]]
==== 縲窟PI 繧ｭ繝ｼ逋ｺ陦檎畑 API 繧ｭ繝ｼ縲阪・逋ｺ陦・莉･荳九・繧医≧縺ｫ API 繧ｭ繝ｼ逋ｺ陦後・ API (`POST /api-keys`) 繧剃ｽｿ縺｣縺ｦ縲、PI 繧ｭ繝ｼ縺ｮ逋ｺ陦後ｒ隕∵ｱゅ＠縺ｾ縺吶・
....
POST /api-keys
Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l

{
  "description":"繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ縺ｮ API 逋ｺ陦檎畑 API 繧ｭ繝ｼ",
  "ownerId":"550e8400-e29b-41d4-a716-446655440000",
  "policies":[
    {
      "effect":"Allow",
      "actions":["List"],
      "resources":[{
          "resourceType": "customer"
      }]
    },{
      "effect":"Allow",
      "actions":["*"],
      "resources":[{
          "resourceType": "api-key"
      }
    ]
  }]
}
....

Authorization 繝倥ャ繝縺ｫ縺ｯ縲仝DTO 縺ｮ邂｡逅・・い繧ｫ繧ｦ繝ｳ繝医・ Basic 隱崎ｨｼ諠・ｱ繧呈欠螳壹＠縺ｾ縺吶・
API 繧ｭ繝ｼ縺ｮ繧ｪ繝ｼ繝翫・ (`ownerId`) 縺ｫ縺ｯ縲・<api-keys-service-registration>>縺ｧ蜈･謇九＠縺溘し繝ｼ繝薙せ ID 繧呈欠螳壹＠縺ｾ縺吶・
繝昴Μ繧ｷ (`policies`) 縺ｫ縺ｯ縲∫匱陦後☆繧・API 繧ｭ繝ｼ縺後←縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ縺ｫ蟇ｾ縺励※縺ｩ縺ｮ繧医≧縺ｪ謫堺ｽ懊ｒ險ｱ蜿ｯ縺輔ｌ繧九°繧貞ｮ夂ｾｩ縺励∪縺吶・縺薙％縺ｧ縺ｯ縲√％縺ｮ API 繧ｭ繝ｼ縺ｧ繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ縺ｮ API 繧ｭ繝ｼ繧堤匱陦後☆繧九◆繧√↓蠢・ｦ√↑繧ｫ繧ｹ繧ｿ繝・ID 繧貞盾辣ｧ縺ｧ縺阪ｋ繧医≧縺ｫ縲・`actions` 縺ｫ `List` 縺ｨ `resourceType` 縺ｫ `customer` 繧呈欠螳壹＠縺ｦ縺・∪縺吶・縺ｾ縺溘√ョ繝ｼ繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ縺ｮ API 繧ｭ繝ｼ縺ｮ邂｡逅・(逋ｺ陦後∵峩譁ｰ縲∝炎髯､) 繧定｡後≧縺溘ａ縺ｫ蠢・ｦ√↑讓ｩ髯舌ｒ荳弱∴繧九◆繧√↓縲・`actions` 縺ｫ `*` 縺ｨ `resourceType` 縺ｫ `api-key` 繧呈欠螳壹＠縺ｦ縺・∪縺吶・
縺溘□縺励・<api-keys-limitations>>縺ｫ縺ゅｋ繧医≧縺ｫ縲∫樟迥ｶ縺ｧ縺ｯ繧ｫ繧ｹ繧ｿ繝・ID 繧呈署萓帙☆繧・Web API 縺ｯ蜈ｬ髢九＆繧後∪縺帙ｓ縺ｮ縺ｧ縲・莉･荳九・繧医≧縺ｪ繝ｪ繧ｯ繧ｨ繧ｹ繝医ｒ騾∽ｿ｡縺吶ｋ縺薙→縺ｫ縺ｪ繧翫∪縺吶・
....
POST /api-keys
Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l

{
  "description":"繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ縺ｮ API 逋ｺ陦檎畑 API 繧ｭ繝ｼ",
  "ownerId":"550e8400-e29b-41d4-a716-446655440000",
  "policies":[{
      "effect":"Allow",
      "actions":["*"],
      "resources":[{
          "resourceType": "api-key"
    }]
  }]
}
....

謌仙粥縺吶ｋ縺ｨ縲∽ｻ･荳九・繧医≧縺ｫ API 繧ｭ繝ｼ (`secret`) 縺檎匱陦後＆繧後∪縺吶・
....
{
  "secret": "f75646d2-d74b-4fdd-8dd3-8fbefe985d86",
  "description": "繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ縺ｮ API 逋ｺ陦檎畑 API 繧ｭ繝ｼ",
  "ownerId": "550e8400-e29b-41d4-a716-446655440000",
  "policies": ...
}
....

[[api-keys-service-admin-flow]]
=== 繧ｵ繝ｼ繝薙せ邂｡逅・・・菴懈･ｭ

[[api-keys-issue-data-access-key]]
==== 縲後ョ繝ｼ繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ縲阪・逋ｺ陦・
繝ｦ繝ｼ繧ｶ繧・し繝ｼ繝薙せ縺後Μ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｫ繧｢繧ｯ繧ｻ繧ｹ縺吶ｋ縺溘ａ縺ｮ API 繧ｭ繝ｼ縺ｯ縲仝DTO 繧貞茜逕ｨ縺吶ｋ繧ｵ繝ｼ繝薙せ邂｡逅・・′逋ｺ陦後＠縺ｾ縺吶・縺薙・菴懈･ｭ繧偵☆繧九↓縺ｯ縲仝DTO 邂｡逅・・°繧画署萓帙＆繧後ｋ縲窟PI 繧ｭ繝ｼ逋ｺ陦檎畑 API 繧ｭ繝ｼ縲阪′蠢・ｦ√〒縺吶・
縲後ョ繝ｼ繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ縲阪ｒ逋ｺ陦後☆繧九◆繧√↓縺ｯ縲仝eb API (POST /api-keys) 繧貞茜逕ｨ縺励∪縺吶・HTTP 繝ｪ繧ｯ繧ｨ繧ｹ繝医・繝・ム縺ｮ `wdto-api-key` 縺ｫ縺ｯ縲仝DTO 邂｡逅・・°繧画署萓帙＆繧後◆縲窟PI 繧ｭ繝ｼ逋ｺ陦檎畑 API 繧ｭ繝ｼ縲阪ｒ謖・ｮ壹＠縺ｾ縺吶・
縺昴・莉悶・ `ownerId` 繧・`policies` 縺ｮ蜀・ｮｹ縺ｯ縲∫匱陦後☆繧・API 繧ｭ繝ｼ縺ｮ蛻ｩ逕ｨ閠・′繧ｫ繧ｹ繧ｿ繝槭°繧ｵ繝ｼ繝薙せ縺九↓繧医▲縺ｦ逡ｰ縺ｪ繧翫∪縺吶・<<api-keys-issue-data-access-customer>>繧・<api-keys-issue-data-access-service>>繧貞盾辣ｧ縺励※縺上□縺輔＞縲・
[[api-keys-issue-data-access-customer]]
===== 繧ｫ繧ｹ繧ｿ繝槭′ WDTO 縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧貞盾辣ｧ縺吶ｋ蝣ｴ蜷・
`POST /api-keys` 繧剃ｽｿ縺・∽ｻ･荳九・繧医≧縺ｪ繝ｪ繧ｯ繧ｨ繧ｹ繝医ｒ騾∽ｿ｡縺励∪縺吶・
....
POST /api-keys
wdto-api-key: f75646d2-d74b-4fdd-8dd3-8fbefe985d86

{
  "description": "繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ縺ｮ繧ｫ繧ｹ繧ｿ繝槭・繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ",
  "ownerId": "575e4f6a-22e8-4763-b352-f60006735c3d",
  "policies": [
    {
      "effect": "Allow",
      "actions": ["List"],
      "resources": [
        {
          "resourceType": "location",
          "customerId": "575e4f6a-22e8-4763-b352-f60006735c3d"
        },
        {
          "resourceType": "device",
          "customerId": "575e4f6a-22e8-4763-b352-f60006735c3d"
        },
      ]
    },
    {
      "effect": "Allow",
      "actions": ["*"],
      "resources": [
        {
          "resourceType": "subscription",
          "customerId": "575e4f6a-22e8-4763-b352-f60006735c3d"
        }
      ]
    }
  ]
}
....

API 繧ｭ繝ｼ縺ｮ繧ｪ繝ｼ繝翫・ (`ownerId`) 縺ｫ縺ｯ縲√後ョ繝ｼ繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ縲阪ｒ謠蝉ｾ帙☆繧九き繧ｹ繧ｿ繝槭・ ID 繧呈欠螳壹＠縺ｾ縺吶・縺溘□縺励∫樟蝨ｨ縲√き繧ｹ繧ｿ繝・ID 縺ｮ蜿ら・縺吶ｋ Web API 繧呈署萓帙＠縺ｦ縺・∪縺帙ｓ縺ｮ縺ｧ縲・繧ｫ繧ｹ繧ｿ繝・ID 縺ｮ蜿門ｾ玲婿豕輔↓縺､縺・※縺ｯ WDTO 縺ｫ縺雁撫縺・粋繧上○縺上□縺輔＞縲・
逋ｺ陦後☆繧・API 繧ｭ繝ｼ縺ｧ縲〕ocation 縺ｨ device 縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ諠・ｱ繧貞盾辣ｧ縺ｧ縺阪ｋ繧医≧縺ｫ縺吶ｋ縺溘ａ縺ｫ縲・繝昴Μ繧ｷ (`policies`) 縺ｮ 1 縺､縺ｫ縺ｯ `resourceType` 縺ｫ縺ｯ `location` 縺ｨ `device` 繧呈欠螳壹＠縺ｾ縺吶・縺ｾ縺溘√し繝悶せ繧ｯ繝ｪ繝励す繝ｧ繝ｳ縺ｮ逋ｻ骭ｲ繧・峩譁ｰ繧定｡後≧縺溘ａ縺ｫ蠢・ｦ√↑讓ｩ髯舌ｒ荳弱∴繧九◆繧√↓縲√ｂ縺・1 縺､縺ｮ繝昴Μ繧ｷ縺ｫ `actions` 縺ｫ `*` 縺ｨ `resourceType` 縺ｫ `subscription` 繧呈欠螳壹＠縺ｦ縺・∪縺吶・縺昴ｌ縺槭ｌ繝昴Μ繧ｷ荳ｭ縺ｮ `customerId` 縺ｫ縺ｯ縲～ownerId` 縺ｨ蜷後§ ID 繧呈欠螳壹＠縺ｾ縺吶・
謌仙粥縺吶ｋ縺ｨ縲∽ｻ･荳九・繧医≧縺ｫ繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ縺ｮ API 繧ｭ繝ｼ (`secret`) 縺檎匱陦後＆繧後∪縺吶・
....
{
  "customerId": "575e4f6a-22e8-4763-b352-f60006735c3d",
  "description": "繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ縺ｮ繧ｫ繧ｹ繧ｿ繝槭・繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ",
  "id": "175e4f6a-12e8-1763-b352-160006735c3d",
  "secret": "e4d993a2-7e43-4a78-8a39-37f67fa8df95",
  "policies": ...
}
....

[[api-keys-issue-data-access-service]]
===== 繧ｵ繝ｼ繝薙せ縺・WDTO 縺ｸ繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧剃ｽ懈・繝ｻ譖ｴ譁ｰ繝ｻ蜑企勁縺吶ｋ蝣ｴ蜷・
`POST /api-keys` 繧剃ｽｿ縺・∽ｻ･荳九・繧医≧縺ｪ繝ｪ繧ｯ繧ｨ繧ｹ繝医ｒ騾∽ｿ｡縺励∪縺吶・
....
POST /api-keys
wdto-api-key: f75646d2-d74b-4fdd-8dd3-8fbefe985d86

{
  "description": "繧ｵ繝ｳ繝励Ν繧ｵ繝ｼ繝薙せ縺ｮ繧ｵ繝ｼ繝薙せ縺ｮ繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ",
  "ownerId": "575e4f6a-22e8-4763-b352-f60006735c3d",
  "policies": [
    {
      "effect": "Allow",
      "actions": ["*"],
      "resources": [
        {
          "resourceType": "location",
          "customerId": "*"
        },
        {
          "resourceType": "device",
          "customerId": "*"
        }
      ]
    }
  ]
}
....

API 繧ｭ繝ｼ縺ｮ繧ｪ繝ｼ繝翫・ (`ownerId`) 縺ｫ縺ｯ縲√Μ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｸ繧｢繧ｯ繧ｻ繧ｹ縺吶ｋ繧ｵ繝ｼ繝薙せ縺ｮ ID (`serviceId`) 繧呈欠螳壹＠縺ｾ縺吶・
逋ｺ陦後☆繧・API 繧ｭ繝ｼ縺ｧ縲〕ocation 縺ｨ device 縺ｮ繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧呈峩譁ｰ縺ｧ縺阪ｋ繧医≧縺ｫ縺吶ｋ縺溘ａ縺ｫ縲・繝昴Μ繧ｷ (`policies`) 縺ｮ `resourceType` 縺ｫ縺ｯ `location` 縺ｨ `device` 繧呈欠螳壹＠縺ｾ縺吶・莉ｻ諢上・繧ｫ繧ｹ繧ｿ繝槭・繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧呈峩譁ｰ縺吶ｋ蝣ｴ蜷医・<api-keys-issue-data-access-customer>>縺ｨ逡ｰ縺ｪ繧翫～*` 繧呈欠螳壹＠縺ｾ縺吶・
== API 繧ｭ繝ｼ縺ｮ Web API 莉墓ｧ・
=== 繝｡繧ｽ繝・ラ

GET縲￣OST縲￣UT縲．ELETE 縺ｮ蜷・Γ繧ｽ繝・ラ繧偵し繝昴・繝医＠縺ｾ縺吶・
=== 繝ｪ繧ｯ繧ｨ繧ｹ繝医・繝・ム縺ｮ螳夂ｾｩ

<<api-keys-issue-api-key>>縺ｨ<<api-keys-issue-data-access-key>>縺ｧ縲∬ｨｭ螳壹☆繧九・繝・ム縺檎焚縺ｪ繧翫∪縺吶・
[width="100%",cols="15%,85%",options="header",frame="all",grid="all"]
|===
|Name |Doc

|Authorization
|<<api-keys-issue-api-key>>繧偵☆繧句ｴ蜷医↓險ｭ螳壹＠縺ｾ縺吶８DTO 邂｡逅・・い繧ｫ繧ｦ繝ｳ繝医・ Basic 隱崎ｨｼ諠・ｱ縺ｧ縺吶・
|wdto-api-key
|<<api-keys-issue-data-access-key>>繧偵☆繧九◆繧√・ API 繧ｭ繝ｼ縺ｧ縺吶８DTO 邂｡逅・・°繧画署萓帙＆繧後∪縺吶・|===

[[api-keys-request-body]]
=== 繝ｪ繧ｯ繧ｨ繧ｹ繝医・繝・ぅ縺ｮ螳夂ｾｩ
<<api-keys-issue-api-key>>縺ｨ<<api-keys-issue-data-access-key>>縺ｧ蛻ｩ逕ｨ縺吶ｋ Web API 縺ｮ繝ｪ繧ｯ繧ｨ繧ｹ繝医・繝・ぅ縺ｮ讒矩縺ｯ蜈ｱ騾壹〒縺吶・縺励°縺励√◎繧後◇繧後・ API 繧ｭ繝ｼ縺ｧ縺ｮ險ｭ螳夐・岼縺ｯ逡ｰ縺ｪ繧翫∪縺吶・縺ｾ縺溘・<api-keys-issue-data-access-customer>>繧・<api-keys-issue-data-access-service>>縺ｧ遉ｺ縺吶ｈ縺・↓縲・API 繧ｭ繝ｼ縺ｮ `ownerId` 縺後し繝ｼ繝薙せ ID 縺九き繧ｹ繧ｿ繝・ID 縺九↓蠢懊§縺ｦ險ｭ螳夐・岼繧ら焚縺ｪ繧翫∪縺吶・
POST 縺ｮ蝣ｴ蜷医・繝ｪ繧ｯ繧ｨ繧ｹ繝医・繝・ぅ縺ｯ縲〉equired 縺・`yes` 縺ｮ螻樊ｧ繧貞・縺ｦ險ｭ螳壹☆繧句ｿ・ｦ√′縺ゅｊ縺ｾ縺吶・
PUT 縺ｮ蝣ｴ蜷医・縲∵峩譁ｰ縺悟ｿ・ｦ√↑鬆・岼縺ｮ縺ｿ險ｭ螳壹＠縺ｾ縺吶よ峩譁ｰ蜿ｯ閭ｽ縺ｪ螻樊ｧ縺ｯ `updatable` 縺・`yes` 縺ｮ繧ゅ・縺ｧ縺吶・
[width="100%",cols="15%,20%,10%,10%,45%",options="header",frame="all",grid="all"]
|===
|Name |Type |required |updatable |Doc

|description
|string
|yes
|yes
|API 繧ｭ繝ｼ縺ｮ陬懆ｶｳ逧・↑諠・ｱ縺ｧ縺吶・
|ownerId
|string
|yes
|no
|API 繧ｭ繝ｼ縺ｮ繧ｪ繝ｼ繝翫・縺ｮ ID 縺ｧ縺吶・+
繧ｫ繧ｹ繧ｿ繝槭′繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｫ繧｢繧ｯ繧ｻ繧ｹ縺吶ｋ縺溘ａ縺ｫ縲√き繧ｹ繧ｿ繝槭↓ API 繧ｭ繝ｼ繧呈署萓帙☆繧句ｴ蜷医・繧ｫ繧ｹ繧ｿ繝・ID縺ｧ縺吶・繧ｵ繝ｼ繝薙せ縺後Μ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｫ繧｢繧ｯ繧ｻ繧ｹ繧句ｴ蜷医・繧ｵ繝ｼ繝薙せ縺ｮ ID 縺ｧ縺吶・
|policies
|array++<++<<attribute-policies>>++>++
|yes
|yes
|<<attribute-policies>> 繝・・繧ｿ縺ｧ縺吶・|===

[[attribute-policies]]
==== policy

[width="100%",cols="15%,20%,10%,10%,45%",options="header",frame="all",grid="all"]
|===
|Name |Type |required |updatable |Doc

|effect
|string(enum)
|yes
|yes
|縲瑚ｨｱ蜿ｯ縺吶ｋ縲阪°縲梧拠蜷ｦ縺吶ｋ縲阪・繝ｪ繧ｷ縺ｪ縺ｮ縺狗､ｺ縺励∪縺吶る∈謚櫁い縺ｯ `Allow` 縺ｾ縺溘・ `Deny` 縺ｧ縺吶・迴ｾ蝨ｨ縺ｯ縲～Allow` 縺ｮ縺ｿ繧偵し繝昴・繝医＠縺ｦ縺・∪縺吶・
|actions
|array<string(enum)>
|yes
|yes
|繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ縺ｫ蟇ｾ縺励※險ｱ蜿ｯ縺ｾ縺溘・諡貞凄縺吶ｋ謫堺ｽ懊ｒ遉ｺ縺励∪縺吶・驕ｸ謚櫁い縺ｯ `List`縲～Create`縲～Update`縲～Delete` 縺ｧ縺吶・蜈ｨ縺ｦ縺ｮ謫堺ｽ懊ｒ險ｱ蜿ｯ縺吶ｋ蝣ｴ蜷医・ `*` 縺ｧ縺吶・
|resources
|array++<++<<api-keys-attribute-resources>>++>++
|yes
|yes
|繝昴Μ繧ｷ縺碁←逕ｨ縺輔ｌ繧・<<api-keys-attribute-resources>> 縺ｧ縺吶・|===

[[api-keys-attribute-resources]]
==== resource

[width="100%",cols="15%,20%,10%,10%,45%",options="header",frame="all",grid="all"]
|===
|Name |Type |required |updatable |Doc

|resourceType
|string
|yes
|yes
|繝昴Μ繧ｷ縺碁←逕ｨ縺輔ｌ繧九Μ繧ｽ繝ｼ繧ｹ縺ｮ遞ｮ鬘槭〒縺吶・+
Authorization 繝倥ャ繝縺ｫ WDTO 邂｡逅・・い繧ｫ繧ｦ繝ｳ繝医・隱崎ｨｼ諠・ｱ縺瑚ｨｭ螳壹＆繧後※縺・ｋ蝣ｴ蜷・ (<<api-keys-issue-api-key>>繧偵☆繧句ｴ蜷・ 縺ｮ驕ｸ謚櫁い縺ｯ `api-key` 縺ｮ縺ｿ縺ｧ縺吶Ａcustomer` 縺ｯ縺ｾ縺謖・ｮ壹〒縺阪∪縺帙ｓ縲・+
wdto-api-key 繝倥ャ繝縺ｫ<<api-keys-issue-data-access-key>>繧偵☆繧句ｴ蜷医・驕ｸ謚櫁い縺ｯ `location`縲～device`縲～subscription` 縺ｧ縺吶・
|customerId
|string
|yes
|yes
|繝昴Μ繧ｷ縺碁←逕ｨ縺輔ｌ繧九Μ繧ｽ繝ｼ繧ｹ縺ｮ繧ｫ繧ｹ繧ｿ繝・ID 縺ｧ縺吶・+
`ownerId` 縺後き繧ｹ繧ｿ繝・ID 縺ｮ蝣ｴ蜷医・縲～ownerId` 縺ｨ蜷後§ ID 縺ｧ縺吶・繧ｵ繝ｼ繝薙せ ID 縺ｮ蝣ｴ蜷医・縺ｿ `*` 繧呈欠螳壹〒縺阪∪縺吶・|===

=== 繝ｬ繧ｹ繝昴Φ繧ｹ縺ｮ繧ｹ繝・・繧ｿ繧ｹ繧ｳ繝ｼ繝・
[width="100%",cols="10%,20%,70%",options="header",frame="all",grid="all"]
|===
|Status Code |Method |Doc

|200
|GET, PUT
|繝ｪ繧ｯ繧ｨ繧ｹ繝医↓謌仙粥縺励◆蝣ｴ蜷医↓霑斐＆繧後∪縺吶・
|201
|POST
|繝ｪ繧ｯ繧ｨ繧ｹ繝医↓謌仙粥縺励◆蝣ｴ蜷医↓霑斐＆繧後∪縺吶・
|204
|DELETE
|繝ｪ繧ｯ繧ｨ繧ｹ繝医↓謌仙粥縺励◆蝣ｴ蜷医↓霑斐＆繧後∪縺吶・
|400
|POST, PUT
|蠢・ｦ√↑諠・ｱ縺後Μ繧ｯ繧ｨ繧ｹ繝医・繝・ぅ縺ｫ險ｭ螳壹＆繧後※縺・↑縺・ｴ蜷医ｄ縲・繝ｪ繧ｯ繧ｨ繧ｹ繝医↓險ｭ螳壹☆繧句､縺ｮ Type 縺・string(enum) 縺ｧ縺ゅｋ蝣ｴ蜷医↓驕ｸ謚櫁い莉･螟悶・蛟､繧定ｨｭ螳壹＠縺溷ｴ蜷医↓霑斐＆繧後∪縺吶・
|400
|POST, PUT
|`ownerId` 縺後き繧ｹ繧ｿ繝・ID 縺ｧ縺ゅｋ蝣ｴ蜷・(繧ｫ繧ｹ繧ｿ繝槭↓繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ縺ｮ API 繧堤匱陦後☆繧句ｴ蜷・ 縺ｫ `ownerId` 縺ｨ蜷後§蛟､縺・`customerId` 縺ｫ險ｭ螳壹＆繧後※縺・↑縺・ｴ蜷医↓霑斐＆繧後∪縺吶・
|401
|縺吶∋縺ｦ
|Authorization 縺ｾ縺溘・ wdto-api-key 繝倥ャ繝縺瑚ｨｭ螳壹＆繧後※縺・↑縺・ｴ蜷医√∪縺溘・隱崎ｨｼ縺ｫ螟ｱ謨励＠縺溷ｴ蜷医↓霑斐＆繧後∪縺吶・
|400
|縺吶∋縺ｦ
|WDTO 邂｡逅・・い繧ｫ繧ｦ繝ｳ繝井ｻ･螟悶〒<<api-keys-issue-api-key>>繧偵＠繧医≧縺ｨ縺励◆蝣ｴ蜷・ (`resourceType` 縺ｫ `api-key` 繧・`customer` 繧定ｨｭ螳壹＠縺溷ｴ蜷・縲√∪縺溘・縲・ API 繧ｭ繝ｼ逋ｺ陦檎畑縺ｮ API 繧ｭ繝ｼ莉･螟悶〒<<api-keys-issue-data-access-key>>繧偵＠繧医≧縺ｨ縺励◆蝣ｴ蜷・ (resourceType 縺ｫ `location` 繧・`device` 繧・`subscription` 繧定ｨｭ螳壹＠縺溷ｴ蜷・ 縺ｫ霑斐＆繧後∪縺吶・
|403
|縺吶∋縺ｦ
|wdto-api-key 繝倥ャ繝縺ｫ謖・ｮ壹＆繧後◆ API 繧ｭ繝ｼ縺ｮ繝昴Μ繧ｷ縺ｧ險ｱ蜿ｯ縺輔ｌ縺ｦ縺・↑縺・ｦ∵ｱゅｒ陦後▲縺溷ｴ蜷医↓霑斐＆繧後∪縺吶・+
萓具ｼ啻actions` 縺ｫ `Create` 縺悟性縺ｾ繧後↑縺・・繝ｪ繧ｷ繧偵ｂ縺､ API 繧ｭ繝ｼ縺ｧ `POST /api-keys` 繧定｡後▲縺溷ｴ蜷医↑縺ｩ縲・
|404
|GET, PUT, DELETE
|蟇ｾ雎｡縺ｮ ID 縺悟ｭ伜惠縺励↑縺・ｴ蜷医↓霑斐＆繧後∪縺吶・|===

=== 繝ｬ繧ｹ繝昴Φ繧ｹ繝懊ョ繧｣

==== GET /api-keys/:id縲￣UT /api-keys/:id縲．ELETE /api-keys/:id 縺ｮ蝣ｴ蜷・
繝ｪ繧ｯ繧ｨ繧ｹ繝医↓謌仙粥縺吶ｋ縺ｨ縲・<api-keys-request-body>>縺ｨ蜷後§讒矩縺ｮ繝ｬ繧ｹ繝昴Φ繧ｹ繝懊ョ繧｣縺瑚ｿ斐＆繧後∪縺吶・
==== GET /api-keys 縺ｮ蝣ｴ蜷・
繝ｪ繧ｯ繧ｨ繧ｹ繝医↓謌仙粥縺吶ｋ縺ｨ縲∽ｻ･荳九・繧医≧縺ｫ API 繧ｭ繝ｼ縺ｮ繝ｪ繧ｹ繝医′霑斐＆繧後∪縺吶・
....
{
  "totalItems": 100,
  "page": 1,
  "itemsPerPage": 20,
  "totalPages": 5,
  "apiKeys": [
    {
      "customerId": "575e4f6a-22e8-4763-b352-f60006735c3d",
      "description": "Customers' API Key",
      "id": "175e4f6a-12e8-1763-b352-160006735c3d",
      "policies": ...
    },
    ...
  ]
}
....

== 繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ API 繧ｭ繝ｼ縺ｫ繧医ｋ Web API 蛻ｶ蠕｡

莉･荳九・ Web API 繧貞茜逕ｨ縺吶ｋ髫帙↓縺ｯ縲√ョ繝ｼ繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ縺ｮ API 繧ｭ繝ｼ繧定ｨｭ螳壹☆繧句ｿ・ｦ√′縺ゅｊ縺ｾ縺吶・
* /devices
* /locations
* /subscriptions

=== /devices縲・locations 蜈ｨ闊ｬ

荳願ｨ倥・ API 縺ｫ蟇ｾ縺吶ｋ蜈ｱ騾壹・蠢懃ｭ比ｻ墓ｧ倥・莉･荳九・騾壹ｊ縺ｧ縺吶・
[width="100%",cols="20%,80%",options="header",frame="all",grid="all"]
|===
|Status Code |Doc

|401
|wdto-api-key 繝倥ャ繝縺瑚ｨｭ螳壹＆繧後※縺・↑縺・ｴ蜷医√∪縺溘・隱崎ｨｼ縺ｫ螟ｱ謨励＠縺溷ｴ蜷医↓霑斐＆繧後∪縺吶・
|403
|wdto-api-key 縺ｮ繝昴Μ繧ｷ縺ｧ險ｱ蜿ｯ縺輔ｌ縺ｦ縺・↑縺・ｦ∵ｱゅｒ陦後▲縺溷ｴ蜷医↓霑斐＆繧後∪縺吶・+
萓具ｼ啻actions` 縺ｫ `Create` 縺悟性縺ｾ繧後※縺・↑縺・・繝ｪ繧ｷ縺ｮ API 繧ｭ繝ｼ縺ｧ `POST /devices` 繧定｡後▲縺溷ｴ蜷医↑縺ｩ
|===

蛟句挨縺ｮ Web API 縺ｮ蠢懃ｭ比ｻ墓ｧ倥・縲∵悽遶縺ｮ蜷・そ繧ｯ繧ｷ繝ｧ繝ｳ縺ｫ遉ｺ縺励∪縺吶・
=== GET /devices縲・locations縲・subscriptions

API 繧ｭ繝ｼ縺ｮ customerId 縺ｫ邏舌▼縺上Μ繧ｽ繝ｼ繧ｹ諠・ｱ縺ｮ縺ｿ繧定ｿ斐＠縺ｾ縺吶・
縺ｪ縺翫・<api-keys-limitations>>縺九ｉ縲∽ｸ縺､縺ｮ API 繧ｭ繝ｼ縺ｧ隍・焚縺ｮ繧ｫ繧ｹ繧ｿ繝槭・繝ｪ繧ｽ繝ｼ繧ｹ縺ｮ繝ｪ繧ｹ繝医ｒ蠕励ｋ縺薙→縺ｯ縺ｧ縺阪∪縺帙ｓ縲・縺昴・縺溘ａ縲√％繧後∪縺ｧ縺ｮ蠢懃ｭ比ｻ墓ｧ倥→蜷後§縺ｧ縺吶・
=== GET /devices:id縲・locations:id縲・subscriptions:id縲．ELETE /devices:id縲・locations:id縲・subscriptions:id

[width="100%",cols="20%,80%",options="header",frame="all",grid="all"]
|===
|Status Code |Doc

|404
|API 繧ｭ繝ｼ縺ｫ險ｭ螳壹＆繧後※縺・ｋ繝昴Μ繧ｷ縺ｮ customerId 縺ｫ邏舌▼縺上Μ繧ｽ繝ｼ繧ｹ ID 縺悟ｭ伜惠縺励↑縺・ｴ蜷医↓霑斐＆繧後∪縺吶・縺薙ｌ縺ｾ縺ｧ縺ｮ蠢懃ｭ比ｻ墓ｧ倥→蜷後§縺ｧ縺吶・|===

=== POST /devices縲・locations

[width="100%",cols="20%,80%",options="header",frame="all",grid="all"]
|===
|Status Code |Doc

|400
|API 繧ｭ繝ｼ縺ｮ繝昴Μ繧ｷ縺ｧ險ｱ蜿ｯ縺輔ｌ縺ｦ縺・↑縺・き繧ｹ繧ｿ繝・ID 縺ｫ蟇ｾ縺吶ｋ繝ｪ繧ｯ繧ｨ繧ｹ繝医ｒ陦後▲縺溷ｴ蜷医↓霑斐＆繧後∪縺吶・縺薙ｌ縺ｾ縺ｧ縺ｮ蠢懃ｭ比ｻ墓ｧ倥→蜷後§縺ｧ縺吶・|===

[[api-keys-limitations]]
== 迴ｾ迥ｶ縺ｮ蛻ｶ邏・
* <<api-keys-service-registration>>縺ｧ蛻ｩ逕ｨ縺吶ｋ縲√し繝ｼ繝薙せ繧堤匳骭ｲ縺吶ｋ縺溘ａ縺ｮ Web API 縺ｯ謠蝉ｾ帙＠縺ｦ縺・∪縺帙ｓ縲・Service ID 縺ｮ逋ｻ骭ｲ縺悟ｿ・ｦ√↑蝣ｴ蜷医・縲仝DTO 縺ｮ髢狗匱閠・↓縺秘｣邨｡縺上□縺輔＞縲・
* <<api-keys-issue-api-key>>菴懈･ｭ縺ｧ縺ｯ縲～resourceType` 縺ｫ `customer` 繧定ｨｭ螳壹〒縺阪∪縺帙ｓ縲・+ 
蟆・擂逧・↓ `GET /customers` 縺ｮ Web API 繧呈署萓帙☆繧九％縺ｨ繧呈Φ螳壹＠縺ｦ縺・∪縺吶′縲∫樟迥ｶ縺ｧ縺ｯ WDTO 邂｡逅・・′繧ｫ繧ｹ繧ｿ繝樊ュ蝣ｱ繧貞盾辣ｧ縺吶ｋ縺溘ａ縺ｮ Web API 縺ｯ謠蝉ｾ帙＆繧後↑縺・°繧峨〒縺吶・
* <<api-keys-issue-api-key>>縺ｫ縺翫＞縺ｦ縲、PI 繧ｭ繝ｼ縺ｮ繧ｪ繝ｼ繝翫′繧ｵ繝ｼ繝薙せ縺ｧ縺ゅｋ蝣ｴ蜷医～resourceType` 縺ｫ `subscription` 繧呈欠螳壹☆繧九％縺ｨ縺ｯ縺ｧ縺阪∪縺帙ｓ縲ら樟迥ｶ縲・`POST /subscriptions` 縺ｯ繧ｫ繧ｹ繧ｿ繝槭′蛻ｩ逕ｨ縺吶ｋ諠ｳ螳壹〒縺ゅｊ縲√し繝悶せ繧ｯ繝ｪ繝励す繝ｧ繝ｳ逋ｻ骭ｲ (縺ｮ繝ｬ繧ｹ繝昴Φ繧ｹ) 縺ｫ繧ｫ繧ｹ繧ｿ繝・ID 縺悟ｿ・ｦ√〒縺ゅｋ縺溘ａ縺ｧ縺吶・
* 繧ｫ繧ｹ繧ｿ繝槭↓繝・・繧ｿ繧｢繧ｯ繧ｻ繧ｹ逕ｨ縺ｮ API 繧ｭ繝ｼ繧堤匱陦後☆繧句ｴ蜷・(ownerId 縺ｫ繧ｫ繧ｹ繧ｿ繝・ID 繧呈欠螳壹☆繧句ｴ蜷・ 縺ｫ縲…ustomerId 縺ｫ ownerId 縺ｨ逡ｰ縺ｪ繧・ID 繧呈欠螳壹☆繧九％縺ｨ縺ｯ縺ｧ縺阪∪縺帙ｓ縲・
* Service Bus API 縺ｫ縺､縺・※縺ｯ縲、PI 繧ｭ繝ｼ縺ｮ蛻ｶ蠕｡蟇ｾ雎｡螟悶〒縺吶ら炊逕ｱ縺ｯ縲・<limitation-service-bus-api>>繧貞盾辣ｧ縺励※縺上□縺輔＞縲・
[[limitation-service-bus-api]]
=== Service Bus API 繧・API 繧ｭ繝ｼ縺ｮ蟇ｾ雎｡螟悶→縺吶ｋ逅・罰

WDTO 縺梧署萓帙☆繧・Service Bus API 縺ｯ縲∽ｻｻ諢上・繧ｫ繧ｹ繧ｿ繝槭・繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧呈署萓帙☆繧九し繝ｼ繝薙せ縺九ｉ蛻ｩ逕ｨ縺輔ｌ縺ｾ縺吶・縺薙・ Service Bus API 繧剃ｽｿ縺・◆繧√・謗･邯壹く繝ｼ縺ｯ縲仝DTO 縺九ｉ繧ｵ繝ｼ繝薙せ縺ｫ謠蝉ｾ帙＆繧後∽ｻ･荳九・繝昴Μ繧ｷ縺碁←逕ｨ縺輔ｌ縺ｦ縺・∪縺吶・
....
  "policies": [
    {
      "effect": "Allow",
      "actions": ["Update"],
      "resources": [
        {
          "resourceType": "location"
        },
        {
          "resourceType": "device"
        }
      ]
    }
  ]
....


縺､縺ｾ繧翫∫樟迥ｶ縺ｧ縺ｯ縲ヾervice Bus 縺ｮ謗･邯壹く繝ｼ縺ｮ讀懆ｨｼ縺悟・譚･繧後・縲∽ｻｻ諢上・繧ｫ繧ｹ繧ｿ繝槭・繝ｪ繧ｽ繝ｼ繧ｹ繝・・繧ｿ繧呈峩譁ｰ縺ｧ縺阪ｋ繧ｵ繝ｼ繝薙せ縺ｧ縺ゅｋ縺ｨ蛻､譁ｭ縺ｧ縺阪ｋ縺溘ａ縲、PI 繧ｭ繝ｼ縺ｫ繧医ｋ繝昴Μ繧ｷ遒ｺ隱阪・荳崎ｦ√〒縺吶ゅ◎縺ｮ縺溘ａ縲∫樟蝨ｨ縺ｮ蜆ｪ蜈亥ｺｦ繧貞刈蜻ｳ縺励ヾervice Bus API 縺ｯ API 繧ｭ繝ｼ縺ｮ蛻ｶ蠕｡蟇ｾ雎｡螟悶→縺励※縺・∪縺吶・
== 縺昴・莉悶・陬懆ｶｳ

* API 繧ｭ繝ｼ縺ｯ繝上ャ繧ｷ繝･蛹悶＠縺ｦ DB 縺ｫ菫晏ｭ倥＆繧後∪縺吶・+
邏帛､ｱ縺励◆蝣ｴ蜷医、PI 繧ｭ繝ｼ縺ｮ蛟､繧貞叙蠕励〒縺阪∪縺帙ｓ縺ｮ縺ｧ縲∵眠縺励＞ API 繧ｭ繝ｼ繧堤匱陦後☆繧句ｿ・ｦ√′縺ゅｊ縺ｾ縺吶・
